// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPC5LAfUrebP7dar7Tbfsrm8H1KvsW7ok',
    appId: '1:639964903352:android:617a75f2cfdc053124014d',
    messagingSenderId: '639964903352',
    projectId: 'threads-project-b2b06',
    databaseURL: 'https://threads-project-b2b06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'threads-project-b2b06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZIVL-15UwoAvS-HO9QsBKBGoJ8118xys',
    appId: '1:639964903352:ios:33cdf3735c0bcefd24014d',
    messagingSenderId: '639964903352',
    projectId: 'threads-project-b2b06',
    databaseURL: 'https://threads-project-b2b06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'threads-project-b2b06.appspot.com',
    iosBundleId: 'com.example.threadsProject',
  );
}
